/* 	SOLUTION OF PROBLEM 2
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-values terms.
*/

// A function to generate a Fibonacci series.
var fib = function (n) {
	if (n === 0) {
		return 0;
	} else if (n === 1) {
		return 1;
	} else {
		return fib(n - 1) + fib(n - 2);
	}
}	

// A functio to create an array of numbers of fibonacci series till a max limit.
var arrayOfFib = function (max) {
	 var ar = []
	 var i = 0;
	 while (true) {
	 	ar[i] = fib(i);
	 	if (ar[i] >= max) {
	 		ar.pop();
	 		return ar;
	 	}
	 	i++;
	 }
	
	return ar;
}

// computation of sum of even numbers till 4000000 in the fibonacci series
var sum = 0;
var newAr = arrayOfFib(4000000);

for (var j = 0; j < newAr.length; j++) {
	if (newAr[j] % 2 === 0) {
		console.log(newAr[j]);
		sum = sum + newAr[j];
	}
}
console.log(sum); //4613732
